AWSTemplateFormatVersion: 2010-09-09
Description: >-
  lambda-sqs

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3

Resources:
  SimpleQueue:
    Type: AWS::SQS::Queue
  
  SQSPayloadLogger:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that logs the payload of messages sent to an associated SQS queue.
      Runtime: nodejs12.x
      Handler: src/handlers/sqs-payload-logger.sqsPayloadLoggerHandler
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SimpleQueue.Arn
      MemorySize: 128
      Timeout: 25 # Chosen to be less than the default SQS Visibility Timeout of 30 seconds
      Policies:
        - AWSLambdaBasicExecutionRole

  SQSPublisherFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/publisher
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies: 
        - AmazonSQSFullAccess
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  SQSPublisherFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt SQSPublisherFunction.Arn
  SQSPublisherFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt SQSPublisherFunctionRole.Arn
